## Numpy Aggregation Funtion

In [1]:
import numpy as np

In [2]:
arr=np.array([10,20,30,40])


print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.std())
print(arr.var())

100
25.0
40
10
11.180339887498949
125.0


# Indexing And Slicing

##### Access Element

In [ ]:
arr=np.array([1,2,3,4])

print(arr[0])  # First element of array
print(arr[-1]) # Last elenment of array

1
4


##### MultiDimentional

In [ ]:
arr=np.array(
              [
                  [1,2,3],
                  [4,5,6]
              ]
             )


# arr[row,column]

print(arr[0]) # First row 
print(arr[1]) # Second row
print(arr[0,0]) # first row first column element
print(arr[0,1]) # first row second column element
print(arr[0,2]) # first row third column element




[1 2 3]
[4 5 6]
1
2
3


##### Slicing Elements

<p><b>---> arr[start:end:step]</b></p>

In [16]:
arr=np.array([10,20,30,40,50,60])

print(arr[1:3]) # 1 to 2 index
print(arr[:4]) # 0 to 3 index
print(arr[::2]) # index (0,2,4)
print(arr[::-1]) # Reverse 


[20 30]
[10 20 30 40]
[10 30 50]
[60 50 40 30 20 10]


##### Fancy Indexing

In [17]:
arr=np.array([10,20,30,40,50,60])

arr[[0,2,3]]

array([10, 30, 40])

#### Filtering {Boolean masking}

In [19]:
arr=np.array([10,20,30,40,50,60])


arr[arr < 48]

array([10, 20, 30, 40])