# Numpy Tutorial start

In [1]:
import numpy as np

## Numpy Array Properties

### Shape

In [2]:
arr=np.array([[1,2,3],
              [4,5,6]]) # 2 rows, 3 columns 


arr.shape

(2, 3)

### Size (Total number of element)

In [3]:
arr=np.array([[1,2,3],
              [4,5,6]]) # 6 elements in this 2D array


print(f'Size of this array = {arr.size}')

Size of this array = 6


### Array Dimension

In [4]:
array_1d=np.array([1,2,3,4])
array_2d=np.array([[1,2,3],[4,5,5],[10,22,3]])
array_3d=np.array([[[1,2,3],[22,44,10]]])



print(array_1d.ndim)
print(array_2d.ndim)
print(array_3d.ndim)

1
2
3


### Data type

In [5]:
arr=np.array([1,2,3,2.44])

arr.dtype

dtype('float64')

## Numpy Method

#### Changing Data Types

In [6]:
arr=np.array([1.22,3.33,22,8.99])
new_arr=arr.astype(int)

print(new_arr)
print(new_arr.dtype)

[ 1  3 22  8]
int64


### Array Math

In [ ]:
arr=np.array([1,2,3])

print(arr + 2)
print(arr - 0.5)
print(arr * 5)
print(arr / 2)

[3 4 5]
[0.5 1.5 2.5]
[ 5 10 15]
[0.5 1.  1.5]
